default['cms']['joinout_backup']['directory_name'] = "html"
# default['cms']['joinout_backup']['package_name'] = "backwpup_joinOut_2014-09-10_11-39-38.tar.gz"
default['cms']['joinout_backup']['package_name'] = "backwpup_ecf9cd_2014-10-02_03-35-35.tar.gz"
default['cms']['joinout_backup']['date']['year'] = "2014"
default['cms']['joinout_backup']['date']['month'] = "09"
default['cms']['wordpress_old']['db']['name'] = "wordpressdb"
default['cms']['wordpress_old']['db']['user'] = "wordpressuser"
default['cms']['wordpress_old']['db']['pass'] = nil
default['cms']['wordpress_old']['db']['host'] = 'localhost'
default['cms']['wordpress_new']['db']['name'] = "wordpress"
default['cms']['wordpress_new']['db']['user'] = "wordpressuser"
default['cms']['wordpress_new']['db']['pass'] = "123123"
default['cms']['wordpress_new']['db']['host'] = "localhost"
default['cms']['wordpressuser']['name'] = "wordpressUser"
default['cms']['wordpressuser']['password']['hash'] = "$1$GZzh5WlV$3b4NwVwokwW2wK9l4ISEw/"
default['cms']['apache']['docroot_dir']
default['cms']['peerjs']['empty_path'] = ""
default['cms']['peerjs']['path'] = "/usr/local/bin/peerjs"
default['cms']['peerjs']['port'] = 443